# Generated by Django 6.0.4 on 2026-04-20 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_mission_question_choice_useranswer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='selected_choice',
            new_name='choice',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='materi_content',
        ),
        migrations.AddField(
            model_name='mission',
            name='content',
            field=models.TextField(default='', help_text='Materi pembelajaran HTML/Markdown untuk misi ini.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='order',
            field=models.IntegerField(default=0, help_text='Urutan misi'),
        ),
        migrations.AlterField(
            model_name='usermissionprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Belum Mulai'), ('reading', 'Sedang Membaca'), ('quiz', 'Sedang Kuis'), ('evaluation', 'Evaluasi'), ('completed', 'Selesai')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='usermissionprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'question')},
        ),
    ]
